context:
  name: antigravity
  version: "1.19.4"
  x86minor: "1772005678"
  arm64minor: "1772005682"
  x86check: "93efa9b6642627b1b0009b5681c6513a"
  arm64check: "ca9e0f3a796486916ccbad3f7456bb7c"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - if: target_platform == "linux-64"
    then:
      url: https://us-central1-apt.pkg.dev/projects/${{ name }}-auto-updater-dev/pool/${{ name }}-debian/${{ name }}_${{ version }}-${{ x86minor }}_amd64_${{ x86check }}.deb
      sha256: c9eb7d8f88588ebbb783af02b112a70a2ec26155938746d09f77fd9f7f20fcca
  - if: target_platform == "linux-aarch64"
    then:
      url: https://us-central1-apt.pkg.dev/projects/${{ name }}-auto-updater-dev/pool/${{ name }}-debian/${{ name }}_${{ version }}-${{ arm64minor }}_arm64_${{ arm64check }}.deb
      sha256: db662052b943cf91a347a08f2f62198f4c0dccc228baa0c6d326bb0c4df10bce

build:
  number: 0
  script: |
    ar x *.deb
    tar -xf data.tar.xz
    
    mkdir -p $PREFIX/share/antigravity
    cp -r usr/share/antigravity/* $PREFIX/share/antigravity/
    
    mkdir -p $PREFIX/bin
    ln -s ../share/antigravity/bin/antigravity $PREFIX/bin/antigravity

requirements:
  build:
    - binutils
    - tar
    - xz
    - menuinst
  host:
    - bash
  run:
    - bash

tests:
  - script:
      - "ls -la $PREFIX/bin/antigravity"
