context:
  name: antigravity
  version: "1.19.6"
  x86minor: "1772152296"
  arm64minor: "1772152278"
  x86check: "4adf927f23143e77a9a759c97e46fe6f"
  arm64check: "f3cf3811643cf91127edc038a2b4257d"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - if: target_platform == "linux-64"
    then:
      url: https://us-central1-apt.pkg.dev/projects/${{ name }}-auto-updater-dev/pool/${{ name }}-debian/${{ name }}_${{ version }}-${{ x86minor }}_amd64_${{ x86check }}.deb
      sha256: 04da15e1db2b7bd9c39708d62a2a42fc4e42ceafd977aac9a638c771117a3d7b
  - if: target_platform == "linux-aarch64"
    then:
      url: https://us-central1-apt.pkg.dev/projects/${{ name }}-auto-updater-dev/pool/${{ name }}-debian/${{ name }}_${{ version }}-${{ arm64minor }}_arm64_${{ arm64check }}.deb
      sha256: 26c096eef1bd18799665fa1784b5b564214059e6a6a227cf5263c2ab9f4301b4
  # Local files needed for the build
  - path: menu
    target_directory: menu
  - path: post-link.sh
  - path: pre-unlink.sh

build:
  number: 0
  script: |
    ar x *.deb
    tar -xf data.tar.xz

    mkdir -p $PREFIX/share/antigravity
    cp -r usr/share/antigravity/* $PREFIX/share/antigravity/

    mkdir -p $PREFIX/bin
    ln -s ../share/antigravity/bin/antigravity $PREFIX/bin/antigravity

    mkdir -p $PREFIX/share/menu
    cp -r menu/*.desktop $PREFIX/share/menu/

    mkdir -p $PREFIX/share/applications
    cp -r menu/*.desktop $PREFIX/share/applications/

    # Install icon to both pixmaps (legacy) and hicolor (modern) locations
    mkdir -p $PREFIX/share/pixmaps
    cp usr/share/pixmaps/antigravity.png $PREFIX/share/pixmaps/antigravity.png

    mkdir -p $PREFIX/share/icons/hicolor/512x512/apps
    cp usr/share/pixmaps/antigravity.png $PREFIX/share/icons/hicolor/512x512/apps/antigravity.png

    # Copy post-link and pre-unlink scripts to prefix and make executable
    cp post-link.sh $PREFIX/
    cp pre-unlink.sh $PREFIX/
    chmod +x $PREFIX/post-link.sh $PREFIX/pre-unlink.sh

    # Create menuinst configuration
    mkdir -p $PREFIX/Menu
    cat << 'EOF' > $PREFIX/Menu/antigravity.json
    {
      "$schema": "https://raw.githubusercontent.com/conda/menuinst/main/menuinst/schema.json",
      "menu_name": "Antigravity",
      "menu_items": [
        {
          "name": "Antigravity",
          "description": "Experience liftoff",
          "icon": "{{ PREFIX }}/share/pixmaps/antigravity.png",
          "command": ["{{ PREFIX }}/bin/antigravity"],
          "platforms": {
            "linux": {}
          }
        }
      ]
    }
    EOF

requirements:
  build:
    - binutils
    - tar
    - xz
  host:
    - bash
  run:
    - bash
    - menuinst >=2

tests:
  - script:
      - "ls -la $PREFIX/bin/antigravity"
      - "test -f $PREFIX/Menu/antigravity.json"
